2.33-0experimental1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/debhelper.in/libc.postinst b/debian/debhelper.in/libc.postinst
--- a/debian/debhelper.in/libc.postinst
+++ b/debian/debhelper.in/libc.postinst
@@ -158,9 +158,18 @@ then
         # Don't bother trying to re-exec init from a chroot:
         TELINIT=no
     elif [ -d /run/systemd/system ]; then
-        # Skip if systemd is the active PID 1, since systemd doesn't
-        # need a reexec for a clean shutdown
+        # Restart systemd on upgrade, but carefully.
+        # The restart is wanted because of LP: #1942276 and Bug: #993821
+        # The care is needed because of https://bugs.debian.org/753725
+        # (if systemd --help fails the system might still be quite broken but
+        # that seems better than the kernel panic that results if systemd
+        # cannot reexec itself).
         TELINIT=no
+        if systemd --help >/dev/null 2>/dev/null; then
+            systemctl daemon-reexec
+        else
+            echo "Error: Could not restart systemd, systemd binary not working" >&2
+        fi
     fi
     if [ "$TELINIT" = "yes" ]; then
         telinit u 2>/dev/null || true ; sleep 1
