2.4-1ubuntu0 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/debhelper.in/libc.postinst b/debian/debhelper.in/libc.postinst
--- a/debian/debhelper.in/libc.postinst
+++ b/debian/debhelper.in/libc.postinst
@@ -1,33 +1,13 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 export LC_ALL=C
+
+type=$1
+preversion=$2
 
 package_name()
 {
     echo LIBC
-}
-
-zone_banner() {
-    TZBase=$(LC_ALL=C TZ=UTC0 date)
-    UTdate=$(TZ=UTC0 date -d "$TZBase")
-    TZdate=$(TZ="$timezone" date -d "$TZBase")
-    extra_info="
-Local time is now:      $TZdate.
-Universal Time is now:  $UTdate."
-    echo "Current default timezone: '$timezone'.$extra_info"
-    echo "Run 'tzconfig' if you wish to change it."
-}
-
-set_timezone() {
-    frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
-    if [ "$frontend" = noninteractive ]; then
-        echo "Non-interactive mode, setting timezone to UTC.  Run tzconfig to change."
-        echo "UTC" >/etc/timezone
-        ln -sf /usr/share/zoneinfo/UTC /etc/localtime
-    else
-        echo "Running 'tzconfig' to set this system's timezone."
-        /usr/sbin/tzconfig
-    fi
 }
 
 # Borrowed from sysvinit's postinst.
@@ -79,25 +59,6 @@ updatercd() {
 		done
 		shift
 	done
-}
-
-realpath()
-{
-    fname=${1%/} # strips trailing '/'
-    while [ -L "$fname" ]; do
-	oldfname="$fname"
-	fname="$(command ls -l $fname)"
-	fname="${fname#*\> }"
-	if [ "$fname" = . ] ; then
-	    fname="$(dirname $oldfname)"
-	elif echo $fname | grep -vq '^/' - ; then
-	    fname="$(dirname $oldfname)/$fname"
-	fi
-    done
-    pushd $(dirname $fname) > /dev/null
-    fname=$(pwd -P)/$(basename $fname)
-    popd > /dev/null
-    echo $fname
 }
 
 # element() is a helper function for file-rc:
@@ -168,7 +129,7 @@ for suffix in -dbg -dev -pic -prof; do
     fi
 done
 
-if [ "$1" = "configure" ]
+if [ "$type" = "configure" ]
 then
     # Handle upgrades for libdb.so.3. We do this before calling ldconfig,
     # since it will create a symlink for us. Just move everything over. We
@@ -177,11 +138,23 @@ then
     # something weird happened and the new libdb2 is unpacked before we
     # get here.
     if [ -e /lib/libdb.so.3.old ]; then
-	if [ -L /lib/libdb.so.3 -o ! -e /lib/libdb.so.3 ]; then
+	if [ -L /lib/libdb.so.3 ] || [ ! -e /lib/libdb.so.3 ]; then
 	    rm -f /lib/libdb.so.3
 	    cat /lib/libdb.so.3.old > /lib/libdb.so.3
 	fi
 	rm -f /lib/libdb.so.3.old
+    fi
+
+    # Add support for /etc/ld.so.conf.d
+    if dpkg --compare-versions $preversion lt 2.3.999.2-4; then
+	if [ -e /etc/ld.so.conf ]; then
+	    [ -z "$(tail -n 1 /etc/ld.so.conf)" ] || echo >> /etc/ld.so.conf
+	else
+	    touch /etc/ld.so.conf
+	fi
+	if ! grep -q '^include /etc/ld.so.conf.d/.*\.conf$' /etc/ld.so.conf ; then
+	    echo 'include /etc/ld.so.conf.d/*.conf' >> /etc/ld.so.conf
+	fi
     fi
 
     # Handle upgrades when libc-opt package has been installed.
@@ -193,7 +166,7 @@ then
 	# it's first time to install ld.so.hwcappkgs aware packages.  We record
 	# all current hwcap package status.
 	if [ ! -f /etc/ld.so.hwcappkgs ]; then
-	    case $(dpkg --print-installation-architecture) in
+	    case $(dpkg --print-architecture) in
 		i386)
 		    hwcappkgs="libc6 libc6-i686"
 		    ;;
@@ -254,26 +227,30 @@ then
 	fi
     fi
 
-    if [ ! -z $2 ]; then
+    if [ ! -z $preversion ]; then
 	if [ ! -d /var/mail ] && [ ! -L /var/mail ]; then
 	    ln -sf spool/mail /var/mail
 	fi
-	if dpkg --compare-versions $2 lt 2.3.5-1; then
+	if dpkg --compare-versions $preversion lt 2.3.5-1; then
 	    echo -n "Checking for services that may need to be restarted..."
 
-	    check="nis smail sendmail exim ssh netbase"
+	    check="nis smail sendmail exim exim4-base ssh netbase"
 	    check="$check ssh-nonfree postfix-tls wu-ftpd boa cron postfix"
 	    check="$check wu-ftpd-academ vsftpd slapd openldapd wwwoffle"
 	    check="$check cupsys lprng lpr lpr-ppd autofs snmpd ssh-krb5"
 	    check="$check courier-authdaemon mysql-server spamassassin"
 	    check="$check apache apache-ssl apache-perl apache2-common"
 	    check="$check proftpd proftpd-ldap proftpd-mysql proftpd-pgsql"
-	    check="$check dovecot-common cucipop rsync samba"
+	    check="$check dovecot-common cucipop rsync samba saslauthd"
+	    check="$check webmin dropbear"
 	    # Only get the ones that are installed, and configured
 	    check=$(dpkg -s $check 2> /dev/null | egrep '^Package:|^Status:' | awk '{if ($1 ~ /^Package:/) { package=$2 } else if ($0 ~ /^Status: .* installed$/) { print package }}')
 	    # apache2 ships its init script in apache2-common, but the
 	    # script is apache2
 	    check=$(echo $check | sed 's/apache2-common/apache2/g')
+	    # exim4 ships its init script in exim4-base, but the script
+	    # is exim4
+	    check=$(echo $check | sed 's/exim4-base/exim4/g')
 	    # The name of proftpd-{ldap,mysql,pgsql} init script is
 	    # same as "proftpd".
 	    check=$(echo $check | sed 's/proftpd-.*/proftpd/g')
@@ -285,12 +262,12 @@ then
 	    # intentional to not replace lprng.
 	    check=$(echo $check | sed 's/lpr /lpd /g')
 	    check=$(echo $check | sed 's/lpr-ppd /lpd-ppd /g')
-	    # We have to list inetd explicitly, because the package is a
-	    # different name from it's init script
-	    check="$check inetd"
+	    # We have to list inetd and atd explicitly, because the packages
+	    # have different names to their init scripts
+	    check="$check inetd atd"
 	    rl=$(runlevel | awk '{print $2}')
 	    for service in $check; do
-		if [ -f /usr/share/file-rc/rc -o -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
+		if [ -f /usr/share/file-rc/rc ] || [ -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
 		    idl=$(filerc $rl $service)
 		else
 		    idl=$(ls /etc/rc${rl}.d/S??${service} 2> /dev/null | head -1)
@@ -302,24 +279,26 @@ then
 	    echo "done."
 	    if [ -n "$services" ]; then
 		echo
-		echo "Name Service Switch has changed in the C Library: post-installation question."
-		echo "Running programs may not be able to do NSS lookups until they are"
-		echo "restarted (for services such as ssh, this can affect your ability to"
-		echo "login)."
+		echo "Name Service Switch update in the C Library: post-installation question."
+		echo
+		echo "Running services and programs that are using NSS need to be restarted,"
+		echo "otherwise they might not be able to do lookup or authentication any more"
+		echo "(for services such as ssh, this can affect your ability to login)."
 		echo "Note: restarting sshd/telnetd should not affect any existing connections."
 		echo
-		echo "The services detected are: $services"
+		echo "The services detected are: "
+		echo "        $services"
 		echo
-		echo "If other services begin to fail mysteriously after this upgrade,"
-		echo "it may be necessary to restart them too.  We strongly recommend"
-		echo "you to reboot your machine to avoid the NSS related trouble."
+		echo "If other services have begun to fail mysteriously after this upgrade, it is"
+		echo "probably necessary to restart them too.  We recommend you to reboot your"
+		echo "machine after the upgrade to avoid the NSS related trouble."
 		echo
 		frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
 		if [ "$frontend" = noninteractive ]; then
 		    echo "Non-interactive mode, restarting services"
 		    answer=yes
 		else
-		    echo -n "Do you wish to Restart Services? [Y/n] "
+		    echo -n "Do you wish to restart services? [Y/n] "
 		    read answer
 		    case $answer in
 			Y*|y*) answer=yes ;;
@@ -332,7 +311,7 @@ then
 		    echo "Restarting services possibly affected by the upgrade:"
 		    failed=""
 		    for service in $services; do
-			if [ -f /usr/share/file-rc/rc -o -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
+			if [ -f /usr/share/file-rc/rc ] || [ -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
 			    idl=$(filerc $rl $service)
 			else
 			    idl=$(ls /etc/rc${rl}.d/S??${service} 2> /dev/null | head -1)
@@ -367,54 +346,19 @@ then
 		    echo
 		fi
 	    fi
-	fi # end upgrading and $2 lt 2.1.95-1
+	fi # end upgrading and $preversion lt 2.3.5-1
     fi # Upgrading
-    if [ -f /etc/timezone.save ]; then
-	mv -fb /etc/timezone.save /etc/timezone
-    fi
-    if [ -f /etc/timezone ]; then
-	timezone=$(cat /etc/timezone)
-    else
-	timezone=Factory
-    fi
-    if [ "$timezone" = Factory ]; then
-	if [ -L /etc/localtime ]; then
-	    localtime_link=$(realpath /etc/localtime)
-	    if [ -f "$localtime_link" ]; then
-		link_not_dangling=true
-	    fi
-	    if [ "$link_not_dangling" = true ]; then
-		timezone=$(echo $localtime_link | sed 's%^/usr/share/zoneinfo/%%')
-	    fi
-	fi
-    fi
-    if [ -f /usr/share/zoneinfo/$timezone ] && [ "$timezone" != Factory ]
-    then
-#	zic -l $timezone
-	rm -f /etc/localtime && \
-	ln -sf /usr/share/zoneinfo/$timezone /etc/localtime
-	zone_banner
-    # Handle problem caused by lame old tzconfig.
-    elif [ "$timezone" = "US/Pacific-New" ]
-    then
-	echo "US/Pacific" > /etc/timezone
-#	zic -l US/Pacific
-	rm -f /etc/localtime && \
-	ln -sf /usr/share/zoneinfo/US/Pacific /etc/localtime
-	zone_banner
-    else
-	set_timezone
-    fi
-    if [ "$(date +%Z)" = "/etc/localtime" ]; then
-	set_timezone
-    fi
+
+     # Ubuntu change.  Do not do kernel version detection at startup.
+     update-rc.d -f glibc.sh remove >/dev/null 2>&1
+
 #    # DO NOT FOLLOW THIS EXAMPLE IN OTHER PACKAGES
-#    updatercd mountkernfs start 35 S .
-#    if [ -x /usr/sbin/invoke-rc.d ]; then
-#	invoke-rc.d mountkernfs start
-#    else
-#	/etc/init.d/mountkernfs 2>/dev/null || true
-#    fi
+#     updatercd glibc.sh start 01 S .
+#     if [ -x /usr/sbin/invoke-rc.d ]; then
+#	invoke-rc.d glibc.sh start
+#     else
+#	/etc/init.d/glibc.sh 2>/dev/null || true
+#     fi
 fi
 
 if [ "`uname -s`" = Linux ]; then
