2.32-0ubuntu2 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/debhelper.in/libc.postinst b/debian/debhelper.in/libc.postinst
--- a/debian/debhelper.in/libc.postinst
+++ b/debian/debhelper.in/libc.postinst
@@ -29,124 +29,96 @@ then
 
     if [ -n "$preversion" ] && [ -x "$(which ischroot)" ] && ! ischroot; then
 	if dpkg --compare-versions "$preversion" lt GLIBC_VERSION; then
-	    check="apache2.2-common apache apache-ssl apache-perl autofs at"
-	    check="$check boa cucipop courier-authdaemon cron cups exim"
-	    check="$check exim4-base dovecot-common cucipop incron lprng lpr"
-	    check="$check lpr-ppd mysql-server nis openbsd-inetd"
-	    check="$check openldapd postgresql-common proftpd postfix postfix-tls"
-	    check="$check rsync samba sasl2-bin slapd smail sendmail snmpd ssh"
-	    check="$check spamassassin vsftpd wu-ftpd wu-ftpd-academ wwwoffle"
-	    check="$check webmin dropbear gdm"
-	    # NSS services check: 
-	    __NSS_CHECK__
-	    if [ -n "$services" ]; then
+	    check=""
+	    [ -f /var/run/services.need_restart ] && check=$(sort -u /var/run/services.need_restart 2>/dev/null)
+	    # Change service names back into package names, so that we can
+	    # double-check package installation.
+	    check=$(echo "$check" | \
+                    sed -e's/\batd\b/at/g' \
+                        -e's/\bdovecot\b/dovecot-common/g' \
+                        -e's/\bexim4\b/exim4-base/g' \
+                        -e's/\blpd\b/lpr/g' \
+                        -e's/\blpd-ppd\b/lpr-ppd/g' \
+                        -e's/\bmysql\b/mysql-server/g' \
+                        -e's/\bsaslauthd\b/sasl2-bin/g' \
+                        -e's/\bsmbd\b/samba/g' \
+                        -e's/\bpostgresql\b/postgresql-common/g' \
+                    )
 
-	        if [ -f /usr/share/debconf/confmodule ] ; then
-		    db_version 2.0
-		    db_input critical libraries/restart-without-asking || true
-		    db_go || true
-		    db_get libraries/restart-without-asking
-		    if [ "$RET" != true ]; then
-			db_reset glibc/restart-services
-			db_set glibc/restart-services "$services"
-			db_input critical glibc/restart-services || true
-			db_go || true
-			db_get glibc/restart-services
-			if [ "x$RET" != "x" ]
-			then
-			    services="$RET"
+	    # Check to see which of the services that were running at unpack
+	    # time are still around
+            # the following substitution processes the check variable
+            # and returns results in the services variable
+	    # NSS services check:
+	    __NSS_CHECK__
+	    # If there are services that we *stopped* in the preinst, don't
+	    # forget to restart them now
+	    if [ -e /var/run/services.need_start ]; then
+		services="$(sort -u /var/run/services.need_start) $services"
+	    fi
+	    if [ -n "$services" ]; then
+		echo "Restarting services possibly affected by the upgrade:"
+		failed=""
+		for service in $services; do
+		    case "$service" in
+			gdm*)
+			    idlopt="reload"
+			    ;;
+			*)
+			    idlopt="restart"
+			    ;;
+		    esac
+		    echo -n "  $service: restarting..."
+		    if invoke-rc.d ${service} $idlopt > /dev/null 2>&1; then
+			echo "done."
+		    else
+			echo "FAILED! ($?)"
+			failed="$service $failed"
+		    fi
+		done
+	
+		echo
+		if [ -n "$failed" ]; then
+		    if [ -f /usr/share/debconf/confmodule ] ; then
+			db_fset glibc/restart-failed seen false
+			db_subst glibc/restart-failed services "$failed"
+			if [ "$RELEASE_UPGRADE_MODE" = desktop ]; then
+			    db_input medium glibc/restart-failed || true
 			else
-			    services=""
+			    db_input critical glibc/restart-failed || true
+			fi
+			db_go || true
+		    else
+			echo "The following services failed to start: $failed"
+			echo
+			echo "You will need to start these manually by running \`invoke-rc.d <service> start'"
+			echo "If the service still fails to start, you may need to file a bug on"
+			echo "${DPKG_MAINTSCRIPT_PACKAGE}:${DPKG_MAINTSCRIPT_ARCH} or the service involved."
+			frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
+			if [ "$frontend" != noninteractive ]; then
+			    echo
+			    echo -n "Press ENTER to continue: "
+			    read foo
 			fi
 		    fi
 		else
-		    echo
-		    echo "Name Service Switch update in the C Library: post-installation question."
-		    echo
-		    echo "Running services and programs that are using NSS need to be restarted,"
-		    echo "otherwise they might not be able to do lookup or authentication any more"
-		    echo "(for services such as ssh, this can affect your ability to login)."
-		    echo "Note: restarting sshd/telnetd should not affect any existing connections."
-		    echo
-		    echo "The services detected are: "
-		    echo "        $services"
-		    echo
-		    echo "If other services have begun to fail mysteriously after this upgrade, it is"
-		    echo "probably necessary to restart them too.  We recommend that you reboot your"
-		    echo "machine after the upgrade to avoid NSS-related troubles."
-		    echo
-		    frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
-		    if [ "$frontend" = noninteractive ]; then
-		    	echo "Non-interactive mode, restarting services"
-		    	answer=yes
-		    else
-		    	echo -n "Do you wish to restart services? [Y/n] "
-		    	read answer
-		    	case $answer in
-			    N*|n*) services="" ;;
-			    *) ;;
-		        esac
-		    fi
+		    echo "Services restarted successfully."
+		    rm -f /var/run/services.need_start /var/run/services.need_restart
 		fi
-		echo
-		if [ "$services" != "" ]; then
-		    echo "Restarting services possibly affected by the upgrade:"
-		    failed=""
-		    for service in $services; do
-			case "$service" in
-			    gdm)
-				echo -n "  $service: reloading..."
-				if invoke-rc.d ${service} reload > /dev/null 2>&1; then
-				    echo "done."
-				else
-				    echo "FAILED! ($?)"
-				    failed="$service $failed"
-				fi
-				;;
-			    *)
-				echo -n "  $service: restarting..."
-				if invoke-rc.d ${service} restart > /dev/null 2>&1; then
-				    echo "done."
-				else
-				    echo "FAILED! ($?)"
-				    failed="$service $failed"
-				fi
-				;;
-			esac
-		    done
-		    echo
-		    if [ -n "$failed" ]; then
-	        	if [ -f /usr/share/debconf/confmodule ] ; then
-		    	    db_fset glibc/restart-failed seen false
-			    db_subst glibc/restart-failed services "$failed"
-			    db_input critical glibc/restart-failed || true
-			    db_go || true
-			else
-			    echo "The following services failed to start: $failed"
-			    echo
-			    echo "You will need to start these manually by running \`invoke-rc.d <service> start'"
-			    echo "If the service still fails to start, you may need to file a bug on"
-			    echo "${DPKG_MAINTSCRIPT_PACKAGE}:${DPKG_MAINTSCRIPT_ARCH} or the service involved."
-			    frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
-			    if [ "$frontend" != noninteractive ]; then
-			    	echo
-			    	echo -n "Press ENTER to continue: "
-			    	read foo
-			    fi
-			fi
-		    else
-			echo "Services restarted successfully."
-                    fi
-		fi
-                # Shut down the frontend, to make sure none of the
+	
+		# Shut down the frontend, to make sure none of the
 		# restarted services keep a connection open to it
-	        if [ -f /usr/share/debconf/confmodule ] ; then
+		if [ -f /usr/share/debconf/confmodule ] ; then
 		    db_stop
 		fi
 	    else
 		echo "Nothing to restart."
 	    fi
 	fi # end upgrading and $preversion lt GLIBC_VERSION
+	# give a reboot notification on al upgrades (LP: #1546457)
+	if [ -x /usr/share/update-notifier/notify-reboot-required ]; then
+	    /usr/share/update-notifier/notify-reboot-required
+	fi
     fi # Upgrading
 
     # Restart init.  Currently handles chroots, systemd and upstart, and
@@ -160,6 +132,13 @@ then
         # Skip if systemd is the active PID 1, since systemd doesn't
         # need a reexec for a clean shutdown
         TELINIT=no
+    elif [ -x "`which initctl`" ]; then
+        UPSTART=$(initctl version 2>/dev/null | awk '/upstart/ {print $3}' | tr -d ')')
+        if dpkg --compare-versions "$UPSTART" lt-nl 1.6.1; then
+            # This is an old upstart that can't re-exec statefully:
+            TELINIT=no
+            touch /var/run/init.upgraded
+        fi
     fi
     if [ "$TELINIT" = "yes" ]; then
         telinit u 2>/dev/null || true ; sleep 1
diff --git a/debian/debhelper.in/libc.preinst b/debian/debhelper.in/libc.preinst
--- a/debian/debhelper.in/libc.preinst
+++ b/debian/debhelper.in/libc.preinst
@@ -19,6 +19,14 @@ kfreebsd_compare_versions () {
     test $verA -$2 $verB
 }
 
+# libcrypt1 breaks/replaces libc6 (<< 2.31). cannot use a pre-depends on libcrypt1
+# call ldconfig unconditionally for the first libc6 depending on libcrypt1
+if [ -n "$preversion" ] && dpkg --compare-versions "$preversion" lt 2.31-0ubuntu2; then
+	LDCONFIG_NOTRIGGER=y
+	export LDCONFIG_NOTRIGGER
+	ldconfig || ldconfig --verbose
+fi
+
 if [ "$type" != abort-upgrade -a -z "$DPKG_ROOT" ]
 then
     # Load debconf module if available and usable
@@ -181,6 +189,8 @@ then
 	    fi
 
 	    check="kdm postgresql xdm"
+            # the following substitution processes the check variable
+            # and returns results in the services variable
 	    # NSS services check:
 	    __NSS_CHECK__
 	    if [ -n "$services" ]; then 
@@ -188,7 +198,11 @@ then
 	            db_version 2.0
 		    db_reset glibc/upgrade
 		    db_subst glibc/upgrade services $services
-		    db_input critical glibc/upgrade || true
+		    if [ "$RELEASE_UPGRADE_MODE" = desktop ]; then
+			db_input medium glibc/upgrade || true
+		    else
+			db_input critical glibc/upgrade || true
+		    fi
 		    db_go || true
 		    db_get glibc/upgrade
 		    answer=$RET
@@ -231,6 +245,102 @@ then
 	            exit 1
 		fi
 	    fi
+
+            services=""
+            check="apache2 apache apache-ssl apache-perl autofs at"
+            check="$check boa cucipop courier-authdaemon cron cups exim"
+            check="$check exim4-base dovecot-common cucipop incron lprng lpr"
+            check="$check lpr-ppd mysql-server nis openbsd-inetd"
+            check="$check openldapd postgresql-common proftpd postfix postfix-tls"
+            check="$check rsync samba sasl2-bin slapd smail sendmail snmpd ssh"
+            check="$check spamassassin vsftpd wu-ftpd wu-ftpd-academ wwwoffle"
+            check="$check webmin dropbear gdm gdm3"
+            # the following substitution processes the check variable
+            # and returns results in the services variable
+            # NSS services check:
+            __NSS_CHECK__
+            if [ -n "$services" ]; then
+                if [ -f /usr/share/debconf/confmodule ] ; then
+                    db_version 2.0
+                    if [ "$RELEASE_UPGRADE_MODE" = desktop ]; then
+                        db_input medium libraries/restart-without-asking || true
+                    else
+                        db_input critical libraries/restart-without-asking || true
+                    fi
+                    db_go || true
+    
+                    db_get libraries/restart-without-asking
+                    if [ "$RET" != true ]; then
+                        db_reset glibc/restart-services
+                        db_set glibc/restart-services "$services"
+                        if [ "$RELEASE_UPGRADE_MODE" = desktop ]; then
+                            db_input medium glibc/restart-services || true
+                        else
+                            db_input critical glibc/restart-services || true
+                        fi
+                        db_go || true
+                        db_get glibc/restart-services
+                        services="$RET"
+                    fi
+                else
+                    echo
+                    echo "Name Service Switch update in the C Library: post-installation question."
+                    echo
+                    echo "Running services and programs that are using NSS need to be restarted,"
+                    echo "otherwise they might not be able to do lookup or authentication any more"
+                    echo "(for services such as ssh, this can affect your ability to login)."
+                    echo "Note: restarting sshd/telnetd should not affect any existing connections."
+                    echo
+                    echo "The services detected are: "
+                    echo "        $services"
+                    echo
+                    echo "If other services have begun to fail mysteriously after this upgrade, it is"
+                    echo "probably necessary to restart them too.  We recommend that you reboot your"
+                    echo "machine after the upgrade to avoid NSS-related troubles."
+                    echo
+                    frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
+                    if [ "$frontend" = noninteractive ]; then
+                            echo "Non-interactive mode, restarting services"
+                            answer=yes
+                    else
+                            echo -n "Do you wish to restart services? [Y/n] "
+                            read answer
+                            case $answer in
+                            N*|n*) services="" ;;
+                            *) ;;
+                            esac
+                    fi
+                fi
+
+                if [ -n "$services" ]; then
+                    echo "Stopping some services possibly affected by the upgrade (will be restarted later):"
+                    for service in $services; do
+                        case "$service" in
+                            cron)
+                                # See bug (LP: #508083)
+                                echo -n "  $service: stopping..."
+                                if invoke-rc.d ${service} stop > /dev/null 2>&1; then
+                                    echo "done."
+                                    echo "$service" >> /var/run/services.need_start
+                                else
+                                    echo "FAILED! ($?)"
+                                    echo "$service" >> /var/run/services.need_restart
+                                fi
+                              ;;
+
+                            *)
+                                # log service details to allow postinst to handle the
+                                # restart.
+                                echo "$service" >> /var/run/services.need_restart
+                              ;;
+                        esac
+                    done
+    
+                fi
+                echo
+            else
+                echo "Nothing to restart."
+            fi
 	fi # end upgrading and $preversion lt GLIBC_VERSION
     fi # Upgrading
 
